version: '3.1'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: newsletter
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  redis:
    image: redis
    ports:
      - 6379:6379
